### ISSUE TITLE
vignette

### ISSUE THREAD

**Issue by arilamstein** [juliasilge/choroplethrUTCensusTract#2]
I think it would be nice if you had some documentation. On the choroplethrZip package, since it's not on CRAN, I used R-pubs.:

https://github.com/arilamstein/choroplethrZip

For example, it would be nice to see how to find the names (and fips codes) of all the counties in Utah, and how to visualize some sample data.

**Comment by juliasilge** [comment]
Yes, great plan. I just wrote the documentation and updated the README: 
[http://rpubs.com/juliasilge/153515](http://rpubs.com/juliasilge/153515)

**Comment by arilamstein** [comment]
It looks great!
